--- # Poggit-CI Manifest. Open the CI at https://poggit.pmmp.io/ci/iSrDxv/UltraPractice
build-by-default: true
branches:
- stable
projects:
 UltraPractice:
  libs:
    - src: dktapps-pm-pl/pmforms/pmforms
      version: ^2.0.0
...
