# The version of configuration you are using
version: 0

# Put the server in maintenance mode to fix bugs or issues in the arenas :)
mode-maintenance: false

# Your server name
name: "MyServer"

# Your server logo
logo: "https://github.com/iSrDxv"

message-welcome:
 - "-----"
 - "Welcome to Practice Server"
 - "Store: store.myserver.com"
 - "Vote: vote.myserver.com"
 - "Twitter: @MyServer"
 - "-----"

webhooks: 
 status: "https://discord.com/api/webhooks/1008014962205134888/51mv_Fd1gO72tsOJIb0M820jQVyr6c-1z0pHLhWB6OnFuDvx31SCM46bEpdOmSM_owP4"
 ban: "https://discord.com/api/webhooks/1008014723796713482/fOio3-ZuLltJ5jbBU4MPjFuipEwhSLj918tTLtKDG_tRzUHyrZh3Gv2FxrmH-8dMDhdq"